### ISSUE TITLE
imagenet 100 dataset is not available

### ISSUE THREAD

**Issue by gangxu822** [Visual-AI/PromptCCD#3]
https://image-net.org/challenges/LSVRC/2012/index#introduction 
https://image-net.org/challenges/LSVRC/2012/signup
![image](https://github.com/user-attachments/assets/50b7e5f4-40a3-4765-befb-bbe63faee60c)

**Comment by fcendra** [comment]
For the ImageNet 100 dataset, we use the official ImageNet (ILSVRC) 2012 datasets, which you can download from [here](https://image-net.org/download-images.php).

To access the dataset, please follow these steps:
1. **Sign in or create an account**: Make sure to use your institutional email. You will receive a confirmation email to verify your account.
2. **Download access**: Once signed in and granted access, navigate to the **ImageNet Large-scale Visual Recognition Challenge (ILSVRC)** section and select the 2012 challenge.
3. **Select images**: In the **Images** section, choose the Training images (Task 1 & 2) (~130 GB) and Test images (all tasks) (13 GB).
4. **Organize the files**: Follow the directory structure instructions provided [here](https://github.com/Visual-AI/PromptCCD/blob/main/doc/README-data.md#imagenet-100).

I hope this helps! Let me know If you have any further questions.
