### ISSUE TITLE
How do I fix this error when I set args.use_dinov2:true

### ISSUE THREAD

**Issue by gangxu822** [Visual-AI/PromptCCD#5]
![image](https://github.com/user-attachments/assets/0db86289-b9be-46ff-abda-e14fa23cc62f)
args.use_dinov2=true：
![image](https://github.com/user-attachments/assets/8cd8a0b3-7c74-489a-8583-e2ab3ff4bca4)
![image](https://github.com/user-attachments/assets/a3d68056-33df-4b22-9b7c-67e9eafb8e1f)

**Comment by fcendra** [comment]
Hi there,

If you’re having trouble loading the DINOv2 model a.k.a `timm/vit_base_patch14_dinov2.lvd142m`, I recommend first downloading the pretrained weights solely to check whether the model is correctly set up and stored locally. Normally, you shouldn’t need to do this, but if you still encounter the error, there might be an issue with your local setup or connection. You can refer to the documentation [here](https://timm.fast.ai): some timm documentation for detailed instructions on how to do this.

Best regards,
Fernando
