### ISSUE TITLE
how to user dinov2 without error?

### ISSUE THREAD

**Issue by gangxu822** [Visual-AI/PromptCCD#6]
![image](https://github.com/user-attachments/assets/b47f8c12-56c3-4751-90d4-c5f649c3787f)
![image](https://github.com/user-attachments/assets/68dc4a52-1476-425b-83be-e46f82724c8a)
When I use dinov1, it's ok, but when I set use_dinov2 to true, it gives me an error(It's not just the Internet
 problem). I want to use dinov2, just set the variable use_dinov2=True?
![image](https://github.com/user-attachments/assets/5c3611c4-1dff-41a1-9de2-8ff5d1d9d6d2)
![image](https://github.com/user-attachments/assets/81e962d7-44f9-4155-a050-a099b6b3104f)

**Comment by fcendra** [comment]
You may find these links helpful:

- https://blog.csdn.net/youbingchen/article/details/139242394
- https://github.com/Stability-AI/generative-models/issues/315

It appears they are addressing similar issues.

Hope this helps!
