### ISSUE TITLE
Here, the training results are reflected in the four files exp/promptccd_w_gmp_cub/log_Kmeans_eval_stage_*.txt?Which file's indicators shall be the criterion

### ISSUE THREAD

**Issue by gangxu822** [Visual-AI/PromptCCD#7]
![image](https://github.com/user-attachments/assets/7a52526c-3d8e-49d6-986d-47025d689e16)
![image](https://github.com/user-attachments/assets/991ad7b3-842a-470c-b21d-fcf8dc74de51)
![image](https://github.com/user-attachments/assets/7b3f12e8-6e20-4fc1-801c-3c0713e7cc54)
Here, the training results are reflected in the four files exp/promptccd_w_gmp_cub/log_Kmeans_eval_stage_*.txt? Which file's indicators shall be the criterion

**Comment by fcendra** [comment]
Hey there,

To run experiments on PromptCCD, follow these steps:

1. Training Stage: I assume you've already completed this by running:
`CUDA_VISIBLE_DEVICES=%GPU_INDEX% python main.py --config "config/cifar100/cifar100_promptccd_w_gmp.yaml" --train`

2. Test Stage: Execute the following to get your program's results:
`CUDA_VISIBLE_DEVICES=%GPU_INDEX% python main.py --config "exp/%SAVE_PATH%/*.yaml" --test`

The image you attached shows evaluation results from the training stage. Run the test script to see the final results.

Best regards, 
Fernando
